#!/bin/bash

# shellcheck disable=SC2128
_SCRIPTS_PATH="$(dirname -- "${BASH_SOURCE}")"
declare -rx _SCRIPTS_PATH

source "${_SCRIPTS_PATH}/_config"
source "${_SCRIPTS_PATH}/_colors"
source "${_SCRIPTS_PATH}/_aliases"

#------------------------------------------------------------------------#
# Initialize Scripts
#------------------------------------------------------------------------#

# Execute External Script
function execute() {
    local -r script="${_SCRIPTS_PATH}/bin/${1}"
    shift
    "${script}" "$@"
}

# Better pwd and ls
function list { execute "list" "$@"; }

# Read file, store into array/associative array, then stringify
function skim { execute "skimm" "$@"; }

# Compile markdown
function mdcompile { execute "mdcompile" "$@"; }

# Generate README
function readme { execute "readmee" "$@"; }

# Simplify doing Leetcode
function leet { execute "leet" "$@"; }

# Converts string case
function scase { execute "scase" "$@"; }

# _paths require skim to be loaded first
source "${_SCRIPTS_PATH}/_paths"
