#! /bin/bash

[[ -z "${_SCRIPTS_PATH}" ]] && {
    readonly _SCRIPTS_PATH="$( dirname -- "$BASH_SOURCE" )"
    export _SCRIPTS_PATH
}

source "${_SCRIPTS_PATH}/_config"
source "${_SCRIPTS_PATH}/_aliases"

#------------------------------------------------------------------------#
# Initialize Scripts
#------------------------------------------------------------------------#

# Execute External Script
function execute() {
    readonly script="${_SCRIPTS_PATH}/bin/${1}"
    shift
    "${script}" "$@"
}

# Professional Work related scripts
function work { execute "work/${_WORK}/work" "$@"; }
function cic { execute "work/${_WORK}/cic" "$@"; }

# Better pwd and ls
function list { execute "list" "$@"; }

# Read file, store into array/associative array, then stringify
function skim { execute "skimm" "$@"; }

# Compile markdown
function mdcompile { execute "mdcompile" "$@"; }

# Generate README
function readme { execute "readmee" "$@"; }

# Simplify doing Leetcode
function leet { execute "leet" "$@"; }


# _paths require skim to be loaded first
source "${_SCRIPTS_PATH}/_paths"
