#! /bin/bash

[[ -z "${_SCRIPTS_PATH}" ]] && {
    readonly _SCRIPTS_PATH="$( dirname -- "$BASH_SOURCE" )"
    export _SCRIPTS_PATH
}

source "${_SCRIPTS_PATH}/_config"
source "${_SCRIPTS_PATH}/_aliases"
source "${_SCRIPTS_PATH}/_helpers"

#-------------------------------------------------------------------------#
# Initialize Scripts
#-------------------------------------------------------------------------#

# Execute External Script
function execute() {
    local script="${_SCRIPTS_PATH}/bin/$1"
    shift
    "${script}" "$@"
}


# Better pwd and ls
function list { execute "list" "$@"; }

# Read file, store into array/associative array, then stringify
function skim { execute "skim" "$@"; }

# Compile markdown
function mdcompile { execute "mdcompile" "$@"; }


# _paths require skim to be loaded first
source "${_SCRIPTS_PATH}/_paths"
