#! /bin/bash

# Useful for debugging
alias reload=". ~/.bashrc"

# Colored ls and grep by default
alias ls="ls --color=yes"
alias grep="grep --color=always"

# Colored Grep
alias    grey-grep="GREP_COLOR='1;30' grep --color=always"
alias     red-grep="GREP_COLOR='1;31' grep --color=always"
alias   green-grep="GREP_COLOR='1;32' grep --color=always"
alias  yellow-grep="GREP_COLOR='1;33' grep --color=always"
alias    blue-grep="GREP_COLOR='1;34' grep --color=always"
alias magenta-grep="GREP_COLOR='1;35' grep --color=always"
alias    cyan-grep="GREP_COLOR='1;36' grep --color=always"
alias   white-grep="GREP_COLOR='1;37' grep --color=always"

# Latest Python
function py() {
    [[ $# -eq 0 ]] && { "${_PYTHON}"; return; }

    [[ $# -eq 1 ]] \
        && { "${_PYTHON}" "${1}.py"; return; } \
        || { "${_PYTHON}" "${1}.py" "${@:2}"; return; }
}

alias pyy="${_PYTHON}"
alias pip="${_PYTHON} -m pip"

# Python Virtual Environment
alias ve="
    [[ ! -d .venv ]] && "${_PYTHON}" -m venv .venv --upgrade-deps
    source .venv/bin/activate
"

# Python Debugger
function pdb() { "${_PYTHON}" -m pdb "${1}.py"; }

# Python Formatter
function blk() { black "${1}.py"; }

# Generate Readme
function readme() {
    if [[ $# -eq 1 && "$1" == "init" ]]; then
        touch main.md
        mkdir sections
    elif [[ -f "main.md" ]]; then
        mdcompile
        mv compiled.md ../README.md

        echo "Succesfully compiled markdown and generated README"
    else
        echo "file: main.md not found"
    fi
}




