#! /bin/bash

# Useful for debugging
alias reload=". ~/.bashrc"

# Open scripts directory on editor
alias shell="${_EDITOR} ${_SCRIPTS_PATH}/../"

# Colored ls and grep by default
alias ls="ls --color=yes"
alias grep="grep --color=always"

# Colored Grep
alias    grey-grep="GREP_COLOR='1;30' grep --color=always"
alias     red-grep="GREP_COLOR='1;31' grep --color=always"
alias   green-grep="GREP_COLOR='1;32' grep --color=always"
alias  yellow-grep="GREP_COLOR='1;33' grep --color=always"
alias    blue-grep="GREP_COLOR='1;34' grep --color=always"
alias magenta-grep="GREP_COLOR='1;35' grep --color=always"
alias    cyan-grep="GREP_COLOR='1;36' grep --color=always"
alias   white-grep="GREP_COLOR='1;37' grep --color=always"


# Latest Python
function py() {
    if [[ -f "${1}.py" ]]; then
        "${_PYTHON}" "${1}.py" "${@:2}"
    else
        "${_PYTHON}" "${@}"
    fi
}


# Change Python version
function pyc() {
    _PYTHON="python${1}"
}


alias pym="${_PYTHON} -m"
alias pip="pym pip"

# Python Virtual Environment
alias ve="
    [[ ! -d .venv ]] && pym venv .venv --upgrade-deps
    source .venv/bin/activate
"


# Python Pytest
function pyt() {
    if [[ -f "test_${1}.py"  ]]; then
        pytest "test_${1}.py" "${@:2}"
    else
        pytest "${1}" "${@:2}"
    fi
}


# Python Black Formatter with Isort
function blk() {
    if [[ -f "${1}.py"  ]]; then
        isort "${1}.py"
        black "${1}.py" "${@:2}"
    else
        isort "${1}"
        black "${1}" "${@:2}"
    fi
}

