#!/bin/bash

#------------------------------------------------------------------------#
# Configurations
#------------------------------------------------------------------------#

: "${_DEBUG:=false}"
export _DEBUG

: "${_PYTHON:="python3.12"}"
export _PYTHON

: "${_EDITOR:="zed"}"
export _EDITOR

: "${_RESUME_FILE:="mj_sabit_resume.pdf"}"
export _RESUME_FILE

: "${_WORK:=""}"
export _WORK
