#! /bin/bash

#------------------------------------------------------------------------#
# Configurations
#------------------------------------------------------------------------#

[[ -z "${_DEBUG}" ]] &&
    _DEBUG="false"

[[ -z "${_PYTHON}" ]] &&
    _PYTHON="python3.11"

[[ -z "${_EDITOR}" ]] &&
    _EDITOR="subl"

[[ -z "${_RESUME_FILE}" ]] &&
    _RESUME_FILE="mj_sabit_resume.pdf"

[[ -z "${_WORK}" ]] &&
    _WORK="hutility"

export _DEBUG
export _PYTHON
export _EDITOR
export _RESUME_FILE
export _WORK
