#! /bin/bash

#------------------------------------------------------------------------#
# Configurations
#------------------------------------------------------------------------#

[[ -z "${_DEBUG}" ]] && \
    _DEBUG="false"

[[ -z "${_PYTHON}" ]] && \
    _PYTHON="python3.11"

[[ -z "${_EDITOR}" ]] && \
    _EDITOR="subl"

[[ -z "${_WORK}" ]] && \
    _WORK="erudifi"

export _DEBUG
export _PYTHON
export _EDITOR
export _WORK
