#! /bin/bash

# Useful for debugging
alias reload=". ~/.bashrc"

# Open scripts directory on editor
alias shell="${_EDITOR} ${_SCRIPTS_PATH}/../"

# Update apt packages
alias update="sudo apt update && sudo apt upgrade -y"

# Refresh update snap store
alias snupdate="snap-store --quit && sudo snap refresh snap-store"

# Colored ls and grep by default
alias ls="ls --color=yes"
alias grep="grep --color=always"

# Open files app
alias files="xdg-open ."

# Colored Grep
alias    grey-grep="GREP_COLOR='1;30' grep --color=always"
alias     red-grep="GREP_COLOR='1;31' grep --color=always"
alias   green-grep="GREP_COLOR='1;32' grep --color=always"
alias  yellow-grep="GREP_COLOR='1;33' grep --color=always"
alias    blue-grep="GREP_COLOR='1;34' grep --color=always"
alias magenta-grep="GREP_COLOR='1;35' grep --color=always"
alias    cyan-grep="GREP_COLOR='1;36' grep --color=always"
alias   white-grep="GREP_COLOR='1;37' grep --color=always"
