#! /bin/bash

# Django manage.py
function dj () {
    [[ $# -gt 0 ]] && {
        local options=$( getopt -o Mm --long makemigrations:migrate: -- "$@")

        [[ $? -ne 0 ]] && {
            echo "Incorrect options provided"
            exit 1
        }

        eval set -- "${options}"

        while [[ $# -gt 0 ]]; do
            case "$1" in
                -M | --makemigrations) py manage makemigrations; break ;;
                -m | --migrate) py manage migrate; break;;
                --) shift; break ;;
                *) echo; echo "Desc: Django aliases"; echo "Usage: TODO" ;;
            esac
        done
    }
}

# Django extensions
alias sh+="py manage shell_plus"
alias reset_db="py manage reset_db --noinput"
