#!/bin/bash

# Django manage.py
function dj() {
    if [[ $# -gt 0 ]]; then
        local options
        options=$(
            getopt \
                -o p:a:MmxX:ctTs \
                --long startproject:,startapp:makemigrations:migrate:runserver:,_runserver:collectstatic,tailwind_build,tailwind_start,createsuperuser \
                -- "$@"
        )

        [[ $? -ne 0 ]] && {
            log::error "incorrect options provided"
            return 1
        }

        eval set -- "${options}"

        while [[ $# -gt 0 ]]; do
            case "$1" in
            -p | --startproject)
                django-admin startproject "${2}"
                break
                ;;
            -a | --startapp)
                py manage startapp "${2}"
                break
                ;;
            -M | --makemigrations)
                py manage makemigrations
                break
                ;;
            -m | --migrate)
                py manage migrate
                break
                ;;
            -x | --runserver)
                py manage runserver
                break
                ;;
            -X | --_runserver)
                py manage runserver "${@:2}"
                break
                ;;
            -c | --collectstatic)
                py manage collectstatic --noinput
                break
                ;;
            -t | --tailwind_start)
                py manage tailwind start
                break
                ;;
            -T | --tailwind_build)
                py manage tailwind build
                break
                ;;
            -s | --createsuperuser)
                export DJANGO_SUPERUSER_USERNAME="admin"
                export DJANGO_SUPERUSER_EMAIL="admin@email.com"
                export DJANGO_SUPERUSER_PASSWORD="admin"

                py manage createsuperuser --no-input

                unset DJANGO_SUPERUSER_USERNAME
                unset DJANGO_SUPERUSER_EMAIL
                unset DJANGO_SUPERUSER_PASSWORD
                break
                ;;
            --)
                shift
                break
                ;;
            *)
                echo
                printf '%s\n' "Desc: Django aliases"
                printf '%s\n' "Usage: TODO"
                ;;
            esac
        done
    else
        echo
        printf '%s\n' "Desc: Django aliases"
        printf '%s\n' "Usage: TODO"
    fi
}

# Django extensions
alias sh+="py manage shell_plus"
alias reset_db="py manage reset_db --noinput"
