#! /bin/bash

alias branch="reload; git branch --show-current"
alias gm="f() {
    git reset --hard

    if echo \"$PWD\" | grep -qE \"55\"; then
        git checkout staging  # hutility
    else
        git checkout main
    fi
}; f"


# simplify git for solo development
function g() {
    if [[ $# -eq 1 ]]; then
        git add .
        git commit -m "$@"

        if [[ "$(branch)" == "main" ]]; then
            git push
        else
            git push --set-upstream origin "$(branch)"
        fi
    else
        echo
        echo "Usage:"
        echo "  Current directory must be a repo"
        echo
        echo "Args:"
        echo "  Commit Message"
        echo
        echo "Example:"
        echo "  g \"<commit_message>\""
    fi
}


# simplify git add
function ga() {
    if [[ $# -gt 0 ]]; then
        git add "$@"
    else
        git add .
    fi
}


# simplify git commit
alias gc="git commit -m"

# simplify git push, pull
alias gp="git push"
alias gl="git pull"

# simplify push to remote
function gu() { [[ ! -z "$(branch)" ]] && git push --set-upstream origin "$(branch)"; }

# simplify working with git branch
function gb() {
    reload

    if [[ $# -gt 0 ]]; then
        local options=$( getopt -o lc:s:f:d:m: --long list,create:,switch:,find:,delete:,move: -- "$@")

        [[ $? -ne 0 ]] && {
            echo "Incorrect options provided"
            exit 1
        }

        eval set -- "${options}"

        while [[ $# -gt 0 ]]; do
            case "$1" in
                -l | --list)
                    git branch
                    break
                    ;;
                -c | --create)
                    git reset --hard
                    if [[ -z "$(git branch --list "$2")" ]]; then
                        git pull

                        if echo "$PWD" | grep -qE "55"; then
                            git checkout staging  # hutility
                        else
                            git checkout main
                        fi

                        git checkout -b "$2"
                    else
                        git checkout "$2"
                    fi
                    break
                    ;;
                -s | --switch)
                    git reset --hard
                    git checkout "$2"
                    break
                    ;;
                -f | --find)
                    git branch | grep --ignore-case "$2"
                    break
                    ;;
                -d | --delete)
                    git reset --hard

                    if echo "$PWD" | grep -qE "55"; then
                        git checkout staging  # hutility
                    else
                        git checkout main
                    fi

                    git branch -d "$2"
                    break
                    ;;
                -m | --move)
                    if [[ $# -lt 4 ]]; then
                        git branch -m "$(branch)" "$2"
                    else
                        git branch -m "$2" "$4"
                    fi
                    break
                    ;;
                --) shift; break ;;
                *) branch; break ;;
            esac
        done
    else
        branch
    fi
}
