#! /bin/bash

# Latest Python
function py() {
    if [[ -f "${1}.py" ]]; then
        "${_PYTHON}" "${1}.py" "${@:2}"
    else
        "${_PYTHON}" "${@}"
    fi
}


# Change Python version
function pyc() {
    _PYTHON="python${1}"
}


# Python module
function pym() {
    "${_PYTHON}" -m "$@"
}


# Python package installer
alias pip="pym pip"

# Python Virtual Environment
alias ve="
    [[ ! -d .venv ]] && pym venv .venv --upgrade-deps
    source .venv/bin/activate
"

# Python pip freeze and install
alias freeze="pip freeze > requirements.txt"
alias unfreeze="pip install -r requirements.txt"


# Python Pytest
function pyt() {
    if [[ -f "test_${1}.py"  ]]; then
        pytest "test_${1}.py" "${@:2}"
    else
        pytest "${1}" "${@:2}"
    fi
}


# Python Ruff Linter + Black Formatter with Isort
function blk() {
    local files=""

    if [[ -f "${1}.py"  ]]; then
        files="${1}.py"
    else
        files="${1}"
    fi

    ruff check "${files}" --fix
    black "${files}" "${@:2}"
}
