#! /bin/bash

function resume() {
    local -r input_path="$(extract_value_assoc "${_PATHS}" "downloads")/${_RESUME_FILE}"
    local -r repo_path="$(extract_value_assoc "${_PATHS}" "repos")/seyLu.github.io"

    local commit_msg="feat (resume): "
    if [[ -z "$1" ]]; then
        commit_msg+="update resume"
    else
        commit_msg+="$1"
    fi

    if [[ -f "${input_path}" ]]; then
        if [[ -d "${repo_path}" ]]; then
            gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/ebook -dNOPAUSE -dQUIET -dBATCH -sOutputFile="${repo_path}" "${input_path}"

            cd "${repo_path}" || exit
            g "${commit_msg}"

            rm "${input_path}"
        else
            echo
            echo "${repo_path}"
            echo -e "${RED}Error: Repo does not exist.${ENDCOLOR}"
            echo
        fi
    else
        echo
        echo "${input_path}"
        echo -e "${RED}Error: File does not exist.${ENDCOLOR}"
        echo
    fi
}
